/* Generated by Yosys 0.40+25 (git sha1 171577f90, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

module Reset(clk_i, rstn_i, locked_i, rstn_o, rst_o);
  reg _0_ = 1'h0;
  wire _1_;
  input clk_i;
  wire clk_i;
  input locked_i;
  wire locked_i;
  output rst_o;
  reg rst_o;
  input rstn_i;
  wire rstn_i;
  output rstn_o;
  reg rstn_o;
  always @(posedge clk_i, negedge _0_)
    if (!_0_) rstn_o <= 1'h0;
    else rstn_o <= 1'h1;
  always @(posedge clk_i, negedge _0_)
    if (!_0_) rst_o <= 1'h1;
    else rst_o <= 1'h0;
  always @(posedge clk_i, negedge _1_)
    if (!_1_) _0_ <= 1'h0;
    else _0_ <= 1'h1;
  assign _1_ = rstn_i & locked_i;
endmodule
