// ============================================================================
// 60K RoraLink 8B10B RX-only Short Frame Checker
// ----------------------------------------------------------------------------
// Purpose:
//   Minimal 60K RX checker for 15K -> 60K RoraLink link bring-up.
//   Checks continuous 16-word frames generated by top_15k_roralink_tx_short_frame.
//
// Expected frame payload, repeated every 16 words:
//   word 0 : 32'h1234_5678
//   word 1 : 32'h9ABC_DEF0
//   word 2 : 32'h55AA_C33C
//   word 3 : 32'h0F1E_2D3C
//   ... repeated 4 times ...
//   user_rx_last must assert on word 15.
//
// RoraLink IP configuration assumed:
//   RX-only Simplex / Framing / FlowControl None / BackChannel Timer
//   CRC enabled / Scrambler enabled / Little Endian enabled
//   1 lane / 4 Bytes per lane / 6.25Gbps / real SFP RX lane / 125MHz refclk
// ============================================================================

`timescale 1ns / 1ps

module top (
    input  wire       clk,      // 50MHz board clock, used as RoraLink init clock
    input  wire       rst_n,
    output wire [1:0] O_led
);

// --------------------------------------------------------------------------
// Version marker for ILA
// --------------------------------------------------------------------------
(* keep = "true" *) wire [31:0] ila60s_rx_top_version = 32'h6006_2501;

// --------------------------------------------------------------------------
// RoraLink wires
// --------------------------------------------------------------------------
wire        link_reset;
wire        rl_sys_reset;
wire [31:0] user_rx_data;
wire [3:0]  user_rx_strb;
wire        user_rx_valid;
wire        user_rx_last;
wire        crc_pass_fail_n;
wire        crc_valid;
wire        hard_err;
wire        soft_err;
wire        frame_err;
wire        channel_up;
wire        lane_up;
wire        rx_clk;
wire        gt_pll_ok;
wire        gt_rx_align_link;
wire        gt_rx_pma_lock;
wire        gt_rx_k_lock;

wire        global_rst = ~rst_n;
wire        rx_rst_async = global_rst | rl_sys_reset | link_reset | ~gt_pll_ok;

// User logic reset synchronized to rx_clk.
reg [3:0] rx_rst_shr = 4'hF;
always @(posedge rx_clk or posedge rx_rst_async) begin
    if (rx_rst_async)
        rx_rst_shr <= 4'hF;
    else
        rx_rst_shr <= {rx_rst_shr[2:0], 1'b0};
end
wire rx_rst_base = rx_rst_shr[3];
wire rx_rst      = rx_rst_base | ~channel_up;

// --------------------------------------------------------------------------
// RoraLink IP instance
// --------------------------------------------------------------------------
SerDes_Top u_serdes_top(
    .RoraLink_8B10B_Top_link_reset_o         (link_reset),
    .RoraLink_8B10B_Top_sys_reset_o          (rl_sys_reset),
    .RoraLink_8B10B_Top_user_rx_data_o       (user_rx_data),
    .RoraLink_8B10B_Top_user_rx_strb_o       (user_rx_strb),
    .RoraLink_8B10B_Top_user_rx_valid_o      (user_rx_valid),
    .RoraLink_8B10B_Top_user_rx_last_o       (user_rx_last),
    .RoraLink_8B10B_Top_crc_pass_fail_n_o    (crc_pass_fail_n),
    .RoraLink_8B10B_Top_crc_valid_o          (crc_valid),
    .RoraLink_8B10B_Top_hard_err_o           (hard_err),
    .RoraLink_8B10B_Top_soft_err_o           (soft_err),
    .RoraLink_8B10B_Top_frame_err_o          (frame_err),
    .RoraLink_8B10B_Top_channel_up_o         (channel_up),
    .RoraLink_8B10B_Top_lane_up_o            (lane_up),
    .RoraLink_8B10B_Top_gt_pcs_rx_clk_o      (rx_clk),
    .RoraLink_8B10B_Top_gt_pll_lock_o        (gt_pll_ok),
    .RoraLink_8B10B_Top_gt_rx_align_link_o   (gt_rx_align_link),
    .RoraLink_8B10B_Top_gt_rx_pma_lock_o     (gt_rx_pma_lock),
    .RoraLink_8B10B_Top_gt_rx_k_lock_o       (gt_rx_k_lock),

    .RoraLink_8B10B_Top_user_clk_i           (rx_clk),
    .RoraLink_8B10B_Top_init_clk_i           (clk),
    .RoraLink_8B10B_Top_reset_i              (global_rst),
    .RoraLink_8B10B_Top_user_pll_locked_i    (gt_pll_ok),
    .RoraLink_8B10B_Top_gt_reset_i           (global_rst),
    .RoraLink_8B10B_Top_gt_pcs_rx_reset_i    (global_rst)
);

// --------------------------------------------------------------------------
// 16-word frame checker
// --------------------------------------------------------------------------
localparam [3:0] FRAME_WORDS_M1 = 4'd15;
localparam [15:0] PASS_FRAME_TH = 16'd64;

reg        rx_aligned = 1'b0;
reg [3:0]  rx_word_idx = 4'd0;
reg [31:0] rx_valid_cnt = 32'd0;
reg [31:0] rx_frame_cnt = 32'd0;
reg [31:0] rx_crc_valid_cnt = 32'd0;
reg [31:0] rx_crc_pass_cnt = 32'd0;
reg [15:0] rx_good_frame_cnt = 16'd0;

reg        payload_err_seen = 1'b0;
reg        last_err_seen    = 1'b0;
reg        crc_err_seen     = 1'b0;
reg        hard_err_seen    = 1'b0;
reg        soft_err_seen    = 1'b0;
reg        frame_err_seen   = 1'b0;
reg        strb_err_seen    = 1'b0;
reg        any_err_seen     = 1'b0;
reg        test_pass        = 1'b0;

reg [31:0] first_bad_data   = 32'd0;
reg [31:0] first_bad_expect = 32'd0;
reg [3:0]  first_bad_word_idx = 4'd0;

function [31:0] pattern_word;
    input [1:0] sel;
    begin
        case (sel)
            2'd0: pattern_word = 32'h1234_5678;
            2'd1: pattern_word = 32'h9ABC_DEF0;
            2'd2: pattern_word = 32'h55AA_C33C;
            default: pattern_word = 32'h0F1E_2D3C;
        endcase
    end
endfunction

wire        rx_active       = !rx_rst && channel_up;
wire        rx_fire         = rx_active && user_rx_valid;
wire [31:0] expected_now    = pattern_word(rx_word_idx[1:0]);
wire        exp_last_now    = (rx_word_idx == FRAME_WORDS_M1);
wire        payload_bad_now = rx_fire && rx_aligned && (user_rx_data != expected_now);
wire        strb_bad_now    = rx_fire && rx_aligned && (user_rx_strb != 4'hF);
wire        last_bad_now    = rx_fire && rx_aligned && (user_rx_last != exp_last_now);
wire        crc_bad_now     = rx_active && crc_valid && !crc_pass_fail_n;
wire        any_err_now     = payload_bad_now | strb_bad_now | last_bad_now |
                               crc_bad_now | hard_err | soft_err | frame_err;

always @(posedge rx_clk or posedge rx_rst_base) begin
    if (rx_rst_base) begin
        rx_aligned         <= 1'b0;
        rx_word_idx        <= 4'd0;
        rx_valid_cnt       <= 32'd0;
        rx_frame_cnt       <= 32'd0;
        rx_crc_valid_cnt   <= 32'd0;
        rx_crc_pass_cnt    <= 32'd0;
        rx_good_frame_cnt  <= 16'd0;
        payload_err_seen   <= 1'b0;
        last_err_seen      <= 1'b0;
        crc_err_seen       <= 1'b0;
        hard_err_seen      <= 1'b0;
        soft_err_seen      <= 1'b0;
        frame_err_seen     <= 1'b0;
        strb_err_seen      <= 1'b0;
        any_err_seen       <= 1'b0;
        test_pass          <= 1'b0;
        first_bad_data     <= 32'd0;
        first_bad_expect   <= 32'd0;
        first_bad_word_idx <= 4'd0;
    end else begin
        if (!channel_up) begin
            rx_aligned        <= 1'b0;
            rx_word_idx       <= 4'd0;
            rx_good_frame_cnt <= 16'd0;
            test_pass         <= 1'b0;
        end

        if (hard_err)  hard_err_seen  <= 1'b1;
        if (soft_err)  soft_err_seen  <= 1'b1;
        if (frame_err) frame_err_seen <= 1'b1;

        if (rx_active) begin
            if (crc_valid) begin
                rx_crc_valid_cnt <= rx_crc_valid_cnt + 1'b1;
                if (crc_pass_fail_n)
                    rx_crc_pass_cnt <= rx_crc_pass_cnt + 1'b1;
                else
                    crc_err_seen <= 1'b1;
            end

            if (rx_fire) begin
                rx_valid_cnt <= rx_valid_cnt + 1'b1;

                if (!rx_aligned) begin
                    // Discard data until the first frame boundary, then start
                    // checking from the next received word as word 0.
                    if (user_rx_last) begin
                        rx_aligned  <= 1'b1;
                        rx_word_idx <= 4'd0;
                    end
                end else begin
                    if (payload_bad_now) begin
                        payload_err_seen <= 1'b1;
                        if (!any_err_seen) begin
                            first_bad_data     <= user_rx_data;
                            first_bad_expect   <= expected_now;
                            first_bad_word_idx <= rx_word_idx;
                        end
                    end

                    if (strb_bad_now)
                        strb_err_seen <= 1'b1;

                    if (last_bad_now)
                        last_err_seen <= 1'b1;

                    if (any_err_now)
                        any_err_seen <= 1'b1;

                    if (user_rx_last) begin
                        rx_frame_cnt <= rx_frame_cnt + 1'b1;

                        if (!payload_bad_now && !strb_bad_now && !last_bad_now && !crc_bad_now && !any_err_seen) begin
                            if (rx_good_frame_cnt != 16'hFFFF)
                                rx_good_frame_cnt <= rx_good_frame_cnt + 1'b1;
                        end

                        rx_word_idx <= 4'd0;
                    end else begin
                        rx_word_idx <= rx_word_idx + 1'b1;
                    end
                end
            end

            if ((rx_good_frame_cnt >= PASS_FRAME_TH) &&
                (rx_crc_pass_cnt   >= PASS_FRAME_TH) &&
                !any_err_seen && !hard_err_seen && !soft_err_seen && !frame_err_seen) begin
                test_pass <= 1'b1;
            end
        end
    end
end

// --------------------------------------------------------------------------
// LED
// --------------------------------------------------------------------------
reg [25:0] led_cnt = 26'd0;
always @(posedge rx_clk or posedge rx_rst_base) begin
    if (rx_rst_base)
        led_cnt <= 26'd0;
    else
        led_cnt <= led_cnt + 1'b1;
end

assign O_led[0] = gt_pll_ok & gt_rx_pma_lock & gt_rx_k_lock & lane_up & channel_up;
assign O_led[1] = test_pass ? 1'b1 :
                  any_err_seen ? led_cnt[22] : led_cnt[25];

// --------------------------------------------------------------------------
// ILA signals, search prefix: ila60s_rx_
// --------------------------------------------------------------------------
(* keep = "true" *) wire        ila60s_rx_gt_pll_ok        = gt_pll_ok;
(* keep = "true" *) wire        ila60s_rx_rl_sys_reset     = rl_sys_reset;
(* keep = "true" *) wire        ila60s_rx_link_reset       = link_reset;
(* keep = "true" *) wire        ila60s_rx_rst              = rx_rst;
(* keep = "true" *) wire        ila60s_rx_lane_up          = lane_up;
(* keep = "true" *) wire        ila60s_rx_channel_up       = channel_up;
(* keep = "true" *) wire        ila60s_rx_gt_rx_pma_lock   = gt_rx_pma_lock;
(* keep = "true" *) wire        ila60s_rx_gt_rx_k_lock     = gt_rx_k_lock;
(* keep = "true" *) wire        ila60s_rx_gt_rx_align_link = gt_rx_align_link;

(* keep = "true" *) wire        ila60s_rx_user_rx_valid    = user_rx_valid;
(* keep = "true" *) wire [31:0] ila60s_rx_user_rx_data     = user_rx_data;
(* keep = "true" *) wire [3:0]  ila60s_rx_user_rx_strb     = user_rx_strb;
(* keep = "true" *) wire        ila60s_rx_user_rx_last     = user_rx_last;
(* keep = "true" *) wire        ila60s_rx_fire             = rx_fire;
(* keep = "true" *) wire        ila60s_rx_aligned          = rx_aligned;
(* keep = "true" *) wire [3:0]  ila60s_rx_word_idx         = rx_word_idx;
(* keep = "true" *) wire [31:0] ila60s_rx_expected_now     = expected_now;
(* keep = "true" *) wire [31:0] ila60s_rx_valid_cnt        = rx_valid_cnt;
(* keep = "true" *) wire [31:0] ila60s_rx_frame_cnt        = rx_frame_cnt;
(* keep = "true" *) wire [15:0] ila60s_rx_good_frame_cnt   = rx_good_frame_cnt;

(* keep = "true" *) wire        ila60s_rx_crc_valid        = crc_valid;
(* keep = "true" *) wire        ila60s_rx_crc_pass_fail_n  = crc_pass_fail_n;
(* keep = "true" *) wire [31:0] ila60s_rx_crc_valid_cnt    = rx_crc_valid_cnt;
(* keep = "true" *) wire [31:0] ila60s_rx_crc_pass_cnt     = rx_crc_pass_cnt;
(* keep = "true" *) wire        ila60s_rx_hard_err         = hard_err;
(* keep = "true" *) wire        ila60s_rx_soft_err         = soft_err;
(* keep = "true" *) wire        ila60s_rx_frame_err        = frame_err;

(* keep = "true" *) wire        ila60s_rx_payload_bad_now  = payload_bad_now;
(* keep = "true" *) wire        ila60s_rx_strb_bad_now     = strb_bad_now;
(* keep = "true" *) wire        ila60s_rx_last_bad_now     = last_bad_now;
(* keep = "true" *) wire        ila60s_rx_crc_bad_now      = crc_bad_now;
(* keep = "true" *) wire        ila60s_rx_any_err_now      = any_err_now;
(* keep = "true" *) wire        ila60s_rx_payload_err_seen = payload_err_seen;
(* keep = "true" *) wire        ila60s_rx_strb_err_seen    = strb_err_seen;
(* keep = "true" *) wire        ila60s_rx_last_err_seen    = last_err_seen;
(* keep = "true" *) wire        ila60s_rx_crc_err_seen     = crc_err_seen;
(* keep = "true" *) wire        ila60s_rx_hard_err_seen    = hard_err_seen;
(* keep = "true" *) wire        ila60s_rx_soft_err_seen    = soft_err_seen;
(* keep = "true" *) wire        ila60s_rx_frame_err_seen   = frame_err_seen;
(* keep = "true" *) wire        ila60s_rx_any_err_seen     = any_err_seen;
(* keep = "true" *) wire        ila60s_rx_test_pass        = test_pass;
(* keep = "true" *) wire [31:0] ila60s_rx_first_bad_data   = first_bad_data;
(* keep = "true" *) wire [31:0] ila60s_rx_first_bad_expect = first_bad_expect;
(* keep = "true" *) wire [3:0]  ila60s_rx_first_bad_word_idx = first_bad_word_idx;

endmodule
