// ============================================================================
// 60K RoraLink 8B10B RX-only Segmented Video Packet Checker - B1
// ----------------------------------------------------------------------------
// Purpose:
//   Receive and check the segmented RGB888_32 colorbar packets generated by
//   top_15k_roralink_tx_segmented_colorbar_b1.v.
//   This B1 step validates the 15K -> 60K RoraLink link and the segmented
//   video packet format before connecting DDR/HDMI.
//
// RoraLink IP configuration assumed:
//   RX-only Simplex / Framing / FlowControl None / BackChannel Timer
//   Scrambler enabled / CRC enabled / Little Endian enabled
//   1 lane / 4 Bytes per lane / 6.25Gbps / actual 60K SFP RX lane / 125MHz refclk
// ============================================================================

`timescale 1ns / 1ps

module top (
    input  wire       clk,      // 50MHz board clock, used as RoraLink init clock
    input  wire       rst_n,
    output wire [1:0] O_led,     // 60K board LEDs are active-low

        output wire sfp_tx_disable1,
    output wire sfp_tx_disable2

);
assign  sfp_tx_disable1 = 1'b0;
assign  sfp_tx_disable2 = 1'b0;
// --------------------------------------------------------------------------
// Version marker for ILA
// --------------------------------------------------------------------------
(* keep = "true" *) wire [31:0] ila60v_rx_top_version = 32'h6006_3002;

// --------------------------------------------------------------------------
// RoraLink wires
// --------------------------------------------------------------------------
wire        link_reset;
wire        rl_sys_reset;
wire [31:0] user_rx_data;
wire [3:0]  user_rx_strb;
wire        user_rx_valid;
wire        user_rx_last;
wire        crc_pass_fail_n;
wire        crc_valid;
wire        hard_err;
wire        soft_err;
wire        frame_err;
wire        channel_up;
wire        lane_up;
wire        rx_clk;
wire        gt_pll_ok;
wire        gt_rx_align_link;
wire        gt_rx_pma_lock;
wire        gt_rx_k_lock;

wire        global_rst = ~rst_n;
wire        rx_rst_async = global_rst | rl_sys_reset | link_reset | ~gt_pll_ok;

// User logic reset synchronized to rx_clk.
reg [3:0] rx_rst_shr = 4'hF;
always @(posedge rx_clk or posedge rx_rst_async) begin
    if (rx_rst_async)
        rx_rst_shr <= 4'hF;
    else
        rx_rst_shr <= {rx_rst_shr[2:0], 1'b0};
end
wire rx_rst_base = rx_rst_shr[3];

// --------------------------------------------------------------------------
// RoraLink IP instance
// --------------------------------------------------------------------------
SerDes_Top u_serdes_top(
    .RoraLink_8B10B_Top_link_reset_o         (link_reset),
    .RoraLink_8B10B_Top_sys_reset_o          (rl_sys_reset),
    .RoraLink_8B10B_Top_user_rx_data_o       (user_rx_data),
    .RoraLink_8B10B_Top_user_rx_strb_o       (user_rx_strb),
    .RoraLink_8B10B_Top_user_rx_valid_o      (user_rx_valid),
    .RoraLink_8B10B_Top_user_rx_last_o       (user_rx_last),
    .RoraLink_8B10B_Top_crc_pass_fail_n_o    (crc_pass_fail_n),
    .RoraLink_8B10B_Top_crc_valid_o          (crc_valid),
    .RoraLink_8B10B_Top_hard_err_o           (hard_err),
    .RoraLink_8B10B_Top_soft_err_o           (soft_err),
    .RoraLink_8B10B_Top_frame_err_o          (frame_err),
    .RoraLink_8B10B_Top_channel_up_o         (channel_up),
    .RoraLink_8B10B_Top_lane_up_o            (lane_up),
    .RoraLink_8B10B_Top_gt_pcs_rx_clk_o      (rx_clk),
    .RoraLink_8B10B_Top_gt_pll_lock_o        (gt_pll_ok),
    .RoraLink_8B10B_Top_gt_rx_align_link_o   (gt_rx_align_link),
    .RoraLink_8B10B_Top_gt_rx_pma_lock_o     (gt_rx_pma_lock),
    .RoraLink_8B10B_Top_gt_rx_k_lock_o       (gt_rx_k_lock),

    .RoraLink_8B10B_Top_user_clk_i           (rx_clk),
    .RoraLink_8B10B_Top_init_clk_i           (clk),
    .RoraLink_8B10B_Top_reset_i              (global_rst),
    .RoraLink_8B10B_Top_user_pll_locked_i    (gt_pll_ok),
    .RoraLink_8B10B_Top_gt_reset_i           (global_rst),
    .RoraLink_8B10B_Top_gt_pcs_rx_reset_i    (global_rst)
);

// --------------------------------------------------------------------------
// Packet checker constants
// --------------------------------------------------------------------------
localparam [31:0] MAGIC            = 32'hA55A_6002;
localparam [7:0]  FORMAT_RGB888_32 = 8'h01;
localparam [11:0] H_RES            = 12'd1920;
localparam [11:0] V_RES            = 12'd1080;
localparam [10:0] LAST_LINE        = 11'd1079;
localparam [4:0]  LAST_SEG         = 5'd7;
localparam [11:0] SEG_PIXELS_FULL  = 12'd256;
localparam [11:0] SEG_PIXELS_LAST  = 12'd128;
localparam [11:0] HEADER_WORDS     = 12'd4;
localparam [15:0] PASS_SEG_TH      = 16'd512;
localparam [15:0] STABLE_DELAY_MAX = 16'h3FFF;

// --------------------------------------------------------------------------
// Link stable gate: ignore startup transients after channel_up.
// --------------------------------------------------------------------------
reg [15:0] stable_cnt = 16'd0;
reg        check_enable = 1'b0;

always @(posedge rx_clk or posedge rx_rst_base) begin
    if (rx_rst_base) begin
        stable_cnt   <= 16'd0;
        check_enable <= 1'b0;
    end else begin
        if (!channel_up) begin
            stable_cnt   <= 16'd0;
            check_enable <= 1'b0;
        end else if (!check_enable) begin
            if (stable_cnt == STABLE_DELAY_MAX)
                check_enable <= 1'b1;
            else
                stable_cnt <= stable_cnt + 1'b1;
        end
    end
end

wire rx_active = check_enable && channel_up && !rx_rst_base;
wire rx_fire   = rx_active && user_rx_valid;

// --------------------------------------------------------------------------
// Checker state
// --------------------------------------------------------------------------
reg        rx_aligned = 1'b0;
reg        seq_initialized = 1'b0;
reg [11:0] word_idx = 12'd0;

reg [15:0] cur_frame_id = 16'd0;
reg [10:0] cur_line_id  = 11'd0;
reg [4:0]  cur_seg_id   = 5'd0;
reg [11:0] cur_x_base   = 12'd0;
reg [11:0] cur_payload_words = 12'd0;
reg [7:0]  cur_flags    = 8'd0;

reg [15:0] exp_frame_id = 16'd0;
reg [10:0] exp_line_id  = 11'd0;
reg [4:0]  exp_seg_id   = 5'd0;

reg [31:0] rx_valid_cnt     = 32'd0;
reg [31:0] rx_packet_cnt    = 32'd0;
reg [31:0] rx_crc_valid_cnt = 32'd0;
reg [31:0] rx_crc_pass_cnt  = 32'd0;
reg [15:0] rx_good_seg_cnt  = 16'd0;

reg        packet_err        = 1'b0;
reg        header_err_seen   = 1'b0;
reg        payload_err_seen  = 1'b0;
reg        last_err_seen     = 1'b0;
reg        crc_err_seen      = 1'b0;
reg        strb_err_seen     = 1'b0;
reg        seq_err_seen      = 1'b0;
reg        hard_err_seen     = 1'b0;
reg        soft_err_seen     = 1'b0;
reg        frame_err_seen    = 1'b0;
reg        any_err_seen      = 1'b0;
reg        test_pass         = 1'b0;

reg [31:0] first_bad_data     = 32'd0;
reg [31:0] first_bad_expect   = 32'd0;
reg [11:0] first_bad_word_idx = 12'd0;
reg [15:0] first_bad_frame_id = 16'd0;
reg [10:0] first_bad_line_id  = 11'd0;
reg [4:0]  first_bad_seg_id   = 5'd0;

wire [15:0] w1_frame = user_rx_data[31:16];
wire [10:0] w1_line  = user_rx_data[15:5];
wire [4:0]  w1_seg   = user_rx_data[4:0];
wire [7:0]  w2_format = user_rx_data[31:24];
wire [11:0] w2_x_base = user_rx_data[23:12];
wire [11:0] w2_payload_words = user_rx_data[11:0];
wire [7:0]  w3_flags = user_rx_data[31:24];
wire [11:0] w3_width = user_rx_data[23:12];
wire [11:0] w3_height = user_rx_data[11:0];

function [11:0] segment_x_base;
    input [4:0] s;
    begin
        segment_x_base = {s[3:0], 8'h00};
    end
endfunction

function [11:0] segment_payload_words;
    input [4:0] s;
    begin
        if (s == LAST_SEG)
            segment_payload_words = SEG_PIXELS_LAST;
        else
            segment_payload_words = SEG_PIXELS_FULL;
    end
endfunction

function [7:0] expected_flags;
    input [10:0] line;
    input [4:0] seg;
    begin
        expected_flags = {
            4'b0000,
            (seg == 5'd0),
            (seg == LAST_SEG),
            ((line == LAST_LINE) && (seg == LAST_SEG)),
            ((line == 11'd0) && (seg == 5'd0))
        };
    end
endfunction

function [23:0] colorbar_rgb;
    input [11:0] x;
    input [10:0] y;
    begin
        if (x < 12'd240)
            colorbar_rgb = 24'hFF_FF_FF;
        else if (x < 12'd480)
            colorbar_rgb = 24'hFF_FF_00;
        else if (x < 12'd720)
            colorbar_rgb = 24'h00_FF_FF;
        else if (x < 12'd960)
            colorbar_rgb = 24'h00_FF_00;
        else if (x < 12'd1200)
            colorbar_rgb = 24'hFF_00_FF;
        else if (x < 12'd1440)
            colorbar_rgb = 24'hFF_00_00;
        else if (x < 12'd1680)
            colorbar_rgb = 24'h00_00_FF;
        else
            colorbar_rgb = 24'h00_00_00;
    end
endfunction

function [31:0] expected_payload_word;
    input [11:0] x;
    input [10:0] y;
    begin
        expected_payload_word = {8'h00, colorbar_rgb(x, y)};
    end
endfunction

wire [11:0] payload_idx = word_idx - HEADER_WORDS;
wire [11:0] payload_x   = cur_x_base + payload_idx;
wire [31:0] expected_payload_now = expected_payload_word(payload_x, cur_line_id);
wire [31:0] expected_word_now = (word_idx == 12'd0) ? MAGIC :
                                (word_idx == 12'd1) ? {exp_frame_id, exp_line_id, exp_seg_id} :
                                (word_idx == 12'd2) ? {FORMAT_RGB888_32, segment_x_base(cur_seg_id), segment_payload_words(cur_seg_id)} :
                                (word_idx == 12'd3) ? {expected_flags(cur_line_id, cur_seg_id), H_RES, V_RES} :
                                expected_payload_now;

wire exp_last_now = rx_aligned && (word_idx == (HEADER_WORDS + cur_payload_words - 12'd1));

wire magic_bad_now   = rx_fire && rx_aligned && (word_idx == 12'd0) && (user_rx_data != MAGIC);
wire word1_bad_now   = rx_fire && rx_aligned && (word_idx == 12'd1) && seq_initialized &&
                       ((w1_frame != exp_frame_id) || (w1_line != exp_line_id) || (w1_seg != exp_seg_id));
wire word2_bad_now   = rx_fire && rx_aligned && (word_idx == 12'd2) &&
                       ((w2_format != FORMAT_RGB888_32) ||
                        (w2_x_base != segment_x_base(cur_seg_id)) ||
                        (w2_payload_words != segment_payload_words(cur_seg_id)) ||
                        (cur_seg_id > LAST_SEG));
wire word3_bad_now   = rx_fire && rx_aligned && (word_idx == 12'd3) &&
                       ((w3_flags != expected_flags(cur_line_id, cur_seg_id)) ||
                        (w3_width != H_RES) ||
                        (w3_height != V_RES));
wire header_bad_now  = magic_bad_now | word1_bad_now | word2_bad_now | word3_bad_now;
wire payload_bad_now = rx_fire && rx_aligned && (word_idx >= HEADER_WORDS) &&
                       (word_idx < (HEADER_WORDS + cur_payload_words)) &&
                       (user_rx_data != expected_payload_now);
wire strb_bad_now    = rx_fire && rx_aligned && (user_rx_strb != 4'hF);
wire last_bad_now    = rx_fire && rx_aligned && (user_rx_last != exp_last_now);
wire crc_bad_now     = rx_active && crc_valid && !crc_pass_fail_n;
wire any_now_core    = header_bad_now | payload_bad_now | strb_bad_now | last_bad_now | crc_bad_now;
wire any_err_now     = any_now_core;

// Next expected segment sequence.
function [15:0] next_frame_id_func;
    input [15:0] f;
    input [10:0] l;
    input [4:0] s;
    begin
        if ((l == LAST_LINE) && (s == LAST_SEG))
            next_frame_id_func = f + 1'b1;
        else
            next_frame_id_func = f;
    end
endfunction

function [10:0] next_line_id_func;
    input [10:0] l;
    input [4:0] s;
    begin
        if (s == LAST_SEG) begin
            if (l == LAST_LINE)
                next_line_id_func = 11'd0;
            else
                next_line_id_func = l + 1'b1;
        end else begin
            next_line_id_func = l;
        end
    end
endfunction

function [4:0] next_seg_id_func;
    input [4:0] s;
    begin
        if (s == LAST_SEG)
            next_seg_id_func = 5'd0;
        else
            next_seg_id_func = s + 1'b1;
    end
endfunction

always @(posedge rx_clk or posedge rx_rst_base) begin
    if (rx_rst_base) begin
        rx_aligned          <= 1'b0;
        seq_initialized     <= 1'b0;
        word_idx            <= 12'd0;
        cur_frame_id        <= 16'd0;
        cur_line_id         <= 11'd0;
        cur_seg_id          <= 5'd0;
        cur_x_base          <= 12'd0;
        cur_payload_words   <= 12'd0;
        cur_flags           <= 8'd0;
        exp_frame_id        <= 16'd0;
        exp_line_id         <= 11'd0;
        exp_seg_id          <= 5'd0;
        rx_valid_cnt        <= 32'd0;
        rx_packet_cnt       <= 32'd0;
        rx_crc_valid_cnt    <= 32'd0;
        rx_crc_pass_cnt     <= 32'd0;
        rx_good_seg_cnt     <= 16'd0;
        packet_err          <= 1'b0;
        header_err_seen     <= 1'b0;
        payload_err_seen    <= 1'b0;
        last_err_seen       <= 1'b0;
        crc_err_seen        <= 1'b0;
        strb_err_seen       <= 1'b0;
        seq_err_seen        <= 1'b0;
        hard_err_seen       <= 1'b0;
        soft_err_seen       <= 1'b0;
        frame_err_seen      <= 1'b0;
        any_err_seen        <= 1'b0;
        test_pass           <= 1'b0;
        first_bad_data      <= 32'd0;
        first_bad_expect    <= 32'd0;
        first_bad_word_idx  <= 12'd0;
        first_bad_frame_id  <= 16'd0;
        first_bad_line_id   <= 11'd0;
        first_bad_seg_id    <= 5'd0;
    end else begin
        if (!channel_up || !check_enable) begin
            rx_aligned      <= 1'b0;
            seq_initialized <= 1'b0;
            word_idx        <= 12'd0;
            packet_err      <= 1'b0;
            test_pass       <= 1'b0;
        end

        // Keep these as debug-only startup/stable indicators. They do not block pass.
        if (rx_active && hard_err)  hard_err_seen  <= 1'b1;
        if (rx_active && soft_err)  soft_err_seen  <= 1'b1;
        if (rx_active && frame_err) frame_err_seen <= 1'b1;

        if (rx_active) begin
            if (crc_valid) begin
                rx_crc_valid_cnt <= rx_crc_valid_cnt + 1'b1;
                if (crc_pass_fail_n)
                    rx_crc_pass_cnt <= rx_crc_pass_cnt + 1'b1;
                else
                    crc_err_seen <= 1'b1;
            end

            if (rx_fire) begin
                rx_valid_cnt <= rx_valid_cnt + 1'b1;

                if (!rx_aligned) begin
                    // Discard current partial packet. Check starts after first frame boundary.
                    if (user_rx_last) begin
                        rx_aligned <= 1'b1;
                        word_idx   <= 12'd0;
                        packet_err <= 1'b0;
                    end
                end else begin
                    if (word_idx == 12'd0)
                        packet_err <= 1'b0;

                    if (word_idx == 12'd1) begin
                        cur_frame_id <= w1_frame;
                        cur_line_id  <= w1_line;
                        cur_seg_id   <= w1_seg;

                        if (!seq_initialized) begin
                            exp_frame_id    <= w1_frame;
                            exp_line_id     <= w1_line;
                            exp_seg_id      <= w1_seg;
                            seq_initialized <= 1'b1;
                        end
                    end

                    if (word_idx == 12'd2) begin
                        cur_x_base        <= w2_x_base;
                        cur_payload_words <= w2_payload_words;
                    end

                    if (word_idx == 12'd3)
                        cur_flags <= w3_flags;

                    if (any_now_core) begin
                        packet_err   <= 1'b1;
                        any_err_seen <= 1'b1;
                        if (header_bad_now) begin
                            header_err_seen <= 1'b1;
                            if (word1_bad_now)
                                seq_err_seen <= 1'b1;
                        end
                        if (payload_bad_now)
                            payload_err_seen <= 1'b1;
                        if (strb_bad_now)
                            strb_err_seen <= 1'b1;
                        if (last_bad_now)
                            last_err_seen <= 1'b1;

                        if (!any_err_seen) begin
                            first_bad_data     <= user_rx_data;
                            first_bad_expect   <= expected_word_now;
                            first_bad_word_idx <= word_idx;
                            first_bad_frame_id <= cur_frame_id;
                            first_bad_line_id  <= cur_line_id;
                            first_bad_seg_id   <= cur_seg_id;
                        end
                    end

                    if (user_rx_last) begin
                        rx_packet_cnt <= rx_packet_cnt + 1'b1;

                        if (!(packet_err | any_now_core)) begin
                            if (rx_good_seg_cnt != 16'hFFFF)
                                rx_good_seg_cnt <= rx_good_seg_cnt + 1'b1;
                        end

                        // Update expected sequence based on the packet just received.
                        exp_frame_id <= next_frame_id_func(cur_frame_id, cur_line_id, cur_seg_id);
                        exp_line_id  <= next_line_id_func(cur_line_id, cur_seg_id);
                        exp_seg_id   <= next_seg_id_func(cur_seg_id);
                        word_idx     <= 12'd0;
                        packet_err   <= 1'b0;
                    end else begin
                        word_idx <= word_idx + 1'b1;
                    end
                end
            end

            if ((rx_good_seg_cnt >= PASS_SEG_TH) &&
                (rx_crc_pass_cnt >= PASS_SEG_TH) &&
                !header_err_seen && !payload_err_seen && !strb_err_seen &&
                !last_err_seen && !crc_err_seen) begin
                test_pass <= 1'b1;
            end
        end
    end
end

// --------------------------------------------------------------------------
// Active-low LEDs on the 60K board.
//   O_led[0] ON  = physical/channel link up
//   O_led[1] ON  = B1 segmented packet checker pass
// --------------------------------------------------------------------------
reg [25:0] led_cnt = 26'd0;
always @(posedge rx_clk or posedge rx_rst_base) begin
    if (rx_rst_base)
        led_cnt <= 26'd0;
    else
        led_cnt <= led_cnt + 1'b1;
end

wire link_ok = gt_pll_ok & gt_rx_pma_lock & gt_rx_k_lock & gt_rx_align_link & lane_up & channel_up;

assign O_led[0] = link_ok ? 1'b0 : 1'b1;
assign O_led[1] = test_pass ? 1'b0 :
                  any_err_seen ? led_cnt[22] : led_cnt[25];

// --------------------------------------------------------------------------
// ILA signals, search prefix: ila60v_rx_
// --------------------------------------------------------------------------
(* keep = "true" *) wire        ila60v_rx_gt_pll_ok          = gt_pll_ok;
(* keep = "true" *) wire        ila60v_rx_rl_sys_reset       = rl_sys_reset;
(* keep = "true" *) wire        ila60v_rx_link_reset         = link_reset;
(* keep = "true" *) wire        ila60v_rx_rx_rst_base        = rx_rst_base;
(* keep = "true" *) wire [15:0] ila60v_rx_stable_cnt         = stable_cnt;
(* keep = "true" *) wire        ila60v_rx_check_enable       = check_enable;
(* keep = "true" *) wire        ila60v_rx_lane_up            = lane_up;
(* keep = "true" *) wire        ila60v_rx_channel_up         = channel_up;
(* keep = "true" *) wire        ila60v_rx_gt_rx_pma_lock     = gt_rx_pma_lock;
(* keep = "true" *) wire        ila60v_rx_gt_rx_k_lock       = gt_rx_k_lock;
(* keep = "true" *) wire        ila60v_rx_gt_rx_align_link   = gt_rx_align_link;
(* keep = "true" *) wire        ila60v_rx_user_rx_valid      = user_rx_valid;
(* keep = "true" *) wire [31:0] ila60v_rx_user_rx_data       = user_rx_data;
(* keep = "true" *) wire [3:0]  ila60v_rx_user_rx_strb       = user_rx_strb;
(* keep = "true" *) wire        ila60v_rx_user_rx_last       = user_rx_last;
(* keep = "true" *) wire        ila60v_rx_fire               = rx_fire;
(* keep = "true" *) wire        ila60v_rx_aligned            = rx_aligned;
(* keep = "true" *) wire        ila60v_rx_seq_initialized    = seq_initialized;
(* keep = "true" *) wire [11:0] ila60v_rx_word_idx           = word_idx;
(* keep = "true" *) wire [31:0] ila60v_rx_expected_now       = expected_word_now;
(* keep = "true" *) wire [15:0] ila60v_rx_cur_frame_id       = cur_frame_id;
(* keep = "true" *) wire [10:0] ila60v_rx_cur_line_id        = cur_line_id;
(* keep = "true" *) wire [4:0]  ila60v_rx_cur_seg_id         = cur_seg_id;
(* keep = "true" *) wire [11:0] ila60v_rx_cur_x_base         = cur_x_base;
(* keep = "true" *) wire [11:0] ila60v_rx_cur_payload_words  = cur_payload_words;
(* keep = "true" *) wire [7:0]  ila60v_rx_cur_flags          = cur_flags;
(* keep = "true" *) wire [15:0] ila60v_rx_exp_frame_id       = exp_frame_id;
(* keep = "true" *) wire [10:0] ila60v_rx_exp_line_id        = exp_line_id;
(* keep = "true" *) wire [4:0]  ila60v_rx_exp_seg_id         = exp_seg_id;
(* keep = "true" *) wire [11:0] ila60v_rx_payload_x          = payload_x;
(* keep = "true" *) wire [31:0] ila60v_rx_valid_cnt          = rx_valid_cnt;
(* keep = "true" *) wire [31:0] ila60v_rx_packet_cnt         = rx_packet_cnt;
(* keep = "true" *) wire [31:0] ila60v_rx_crc_valid_cnt      = rx_crc_valid_cnt;
(* keep = "true" *) wire [31:0] ila60v_rx_crc_pass_cnt       = rx_crc_pass_cnt;
(* keep = "true" *) wire [15:0] ila60v_rx_good_seg_cnt       = rx_good_seg_cnt;
(* keep = "true" *) wire        ila60v_rx_crc_valid          = crc_valid;
(* keep = "true" *) wire        ila60v_rx_crc_pass_fail_n    = crc_pass_fail_n;
(* keep = "true" *) wire        ila60v_rx_hard_err           = hard_err;
(* keep = "true" *) wire        ila60v_rx_soft_err           = soft_err;
(* keep = "true" *) wire        ila60v_rx_frame_err          = frame_err;
(* keep = "true" *) wire        ila60v_rx_magic_bad_now      = magic_bad_now;
(* keep = "true" *) wire        ila60v_rx_word1_bad_now      = word1_bad_now;
(* keep = "true" *) wire        ila60v_rx_word2_bad_now      = word2_bad_now;
(* keep = "true" *) wire        ila60v_rx_word3_bad_now      = word3_bad_now;
(* keep = "true" *) wire        ila60v_rx_header_bad_now     = header_bad_now;
(* keep = "true" *) wire        ila60v_rx_payload_bad_now    = payload_bad_now;
(* keep = "true" *) wire        ila60v_rx_strb_bad_now       = strb_bad_now;
(* keep = "true" *) wire        ila60v_rx_last_bad_now       = last_bad_now;
(* keep = "true" *) wire        ila60v_rx_crc_bad_now        = crc_bad_now;
(* keep = "true" *) wire        ila60v_rx_any_err_now        = any_err_now;
(* keep = "true" *) wire        ila60v_rx_header_err_seen    = header_err_seen;
(* keep = "true" *) wire        ila60v_rx_payload_err_seen   = payload_err_seen;
(* keep = "true" *) wire        ila60v_rx_strb_err_seen      = strb_err_seen;
(* keep = "true" *) wire        ila60v_rx_seq_err_seen       = seq_err_seen;
(* keep = "true" *) wire        ila60v_rx_last_err_seen      = last_err_seen;
(* keep = "true" *) wire        ila60v_rx_crc_err_seen       = crc_err_seen;
(* keep = "true" *) wire        ila60v_rx_hard_err_seen      = hard_err_seen;
(* keep = "true" *) wire        ila60v_rx_soft_err_seen      = soft_err_seen;
(* keep = "true" *) wire        ila60v_rx_frame_err_seen     = frame_err_seen;
(* keep = "true" *) wire        ila60v_rx_any_err_seen       = any_err_seen;
(* keep = "true" *) wire        ila60v_rx_test_pass          = test_pass;
(* keep = "true" *) wire [31:0] ila60v_rx_first_bad_data     = first_bad_data;
(* keep = "true" *) wire [31:0] ila60v_rx_first_bad_expect   = first_bad_expect;
(* keep = "true" *) wire [11:0] ila60v_rx_first_bad_word_idx = first_bad_word_idx;
(* keep = "true" *) wire [15:0] ila60v_rx_first_bad_frame_id = first_bad_frame_id;
(* keep = "true" *) wire [10:0] ila60v_rx_first_bad_line_id  = first_bad_line_id;
(* keep = "true" *) wire [4:0]  ila60v_rx_first_bad_seg_id   = first_bad_seg_id;

endmodule
